### ISSUE TITLE
RGB dataset

### ISSUE THREAD

**Issue by yudadabing** [kli8996/HISR-Spectral-Mixup-Heterogeneous-Datasets#1]
Thanks for your exciting work！
I do not know how to generate RGB samples in "/DIV2KRGB/Train_RGB2020_8channels_x4"  when I  train the network.

**Comment by xinzwang** [comment]
The same question!

**Comment by kli8996** [comment]
thank you for your interest in this work, I have uploaded the code for  RGB image generation. They are in the matlab_code folder and named as crop_image_RGB.m and generate_train_DIV2K_train.m
